export const RESET_BACKEND_MESSAGE = "RESET_BACKEND_MESSAGE";
export const RESET_ERROR_STATE = "RESET_ERROR_STATE";
export const SET_DASHBOARD_TAB = "SET_DASHBOARD_TAB";
export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_SIGN_IN = "USER_SIGN_IN";
export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const PLACE_USER_BUY_OFFER = "PLACE_USER_BUY_OFFER";
export const PLACE_USER_SELL_OFFER = "PLACE_USER_SELL_OFFER";
export const GET_USER_BUY_OFFERS = "GET_USER_BUY_OFFERS";
export const GET_USER_SELL_OFFERS = "GET_USER_SELL_OFFERS";
export const GET_ALL_BUY_OFFERS = "GET_USER_BUY_OFFERS";
export const GET_ALL_SELL_OFFERS = "GET_USER_SELL_OFFERS";

export const USER_SIGN_UP_SUCCESSFUL = "USER_SIGN_UP_SUCCESSFUL";
export const USER_SIGN_UP_UNSUCCESSFUL = "USER_SIGN_UP_UNSUCCESSFUL";

export const CRYPTOINFO = {
  Bitcoin: {
    USD: 26028,
    EURO: 24063,
    AUD: 40474,
    CAD: 35270,
    HKD: 204076,
    SGD: 35323,
    TWD: 831446,
  },
  Ethereum: {
    USD: 1642,
    EURO: 1519,
    AUD: 2554,
    CAD: 2226,
    HKD: 12881,
    SGD: 2229,
    TWD: 52481,
  },
  USDT: {
    USD: 0.995,
    EURO: 0.9239,
    AUD: 1.55,
    CAD: 1.35,
    HKD: 7.84,
    SGD: 1.36,
    TWD: 31.93,
  },
};
