export const RESET_BACKEND_MESSAGE = "RESET_BACKEND_MESSAGE";
export const RESET_ERROR_STATE = "RESET_ERROR_STATE";
export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_SIGN_IN = "USER_SIGN_IN";
export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const PLACE_USER_BUY_OFFER = "PLACE_USER_BUY_OFFER";
export const PLACE_USER_SELL_OFFER = "PLACE_USER_SELL_OFFER";
export const GET_USER_BUY_OFFERS = "GET_USER_BUY_OFFERS";
export const GET_USER_SELL_OFFERS = "GET_USER_SELL_OFFERS";
export const GET_ALL_BUY_OFFERS = "GET_USER_BUY_OFFERS";
export const GET_ALL_SELL_OFFERS = "GET_USER_SELL_OFFERS";

export const USER_SIGN_UP_SUCCESSFUL = "USER_SIGN_UP_SUCCESSFUL";
export const USER_SIGN_UP_UNSUCCESSFUL = "USER_SIGN_UP_UNSUCCESSFUL";
